### ISSUE TITLE
returning clones refrences

### ISSUE THREAD

**Issue by mattanbi** [domenic/dict#14]
Hi,
A "readonly" dict could be useful, so that objects returning from the dict.get method would be clones of the original. what do you think?

**Comment by domenic** [comment]
How do you clone an object?

**Comment by mattanbi** [comment]
using lodash.coneDeep for example https://lodash.com/docs#cloneDeep

**Comment by domenic** [comment]
That fails in a variety of common cases, such as Nodes.

In the end this sounds like a different library, maybe lodash-clonedeep-dict, instead of dict.
